--- #YAML:1.0
name:               CGI-Struct
version:            1.11
abstract:           Build structures from CGI data
author:
    - Matthew Fuller <fullermd@over-yonder.net>
license:            bsd
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
